# Generated by Django 3.2.5 on 2021-07-23 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0005_alter_library_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='图书名字', max_length=64)),
                ('c_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, help_text='修改时间')),
                ('author', models.CharField(help_text='图书作者', max_length=32)),
                ('publish', models.CharField(help_text='出版社', max_length=64)),
                ('pub_time', models.DateField(help_text='出版时间')),
                ('ISBN_code', models.CharField(help_text='ISBN唯一码', max_length=36)),
                ('price', models.DecimalField(decimal_places=2, help_text='价格', max_digits=5)),
                ('state', models.IntegerField(choices=[(0, '未上架'), (1, '已上架')], help_text='图书状态')),
                ('library_id', models.ForeignKey(help_text='关联图书馆', null=True, on_delete=django.db.models.deletion.CASCADE, to='library.library')),
            ],
        ),
    ]
