# Generated by Django 3.2.5 on 2021-07-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='library_id',
            new_name='library',
        ),
    ]
