# Generated by Django 3.2.5 on 2021-07-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_library_id_book_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(db_index=True, help_text='图书名字', max_length=64),
        ),
    ]
